FROM nginx:latest
COPY ./www/index.html /usr/share/nginx/html/index.html
COPY ./www/mabdon_dump_w10.raw /usr/share/nginx/html/mabdon_dump_w10.raw
COPY ./www/mabdon.kdbx /usr/share/nginx/html/mabdon.kdbx
